name: Build and Test

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  quick-test:
    name: Quick Test (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install audio dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev

      - name: Check compilation
        run: cargo check --all-targets

      - name: Run tests
        run: cargo test

      - name: Build debug
        run: cargo build

  cross-platform-check:
    name: Cross-platform Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install Linux audio dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev

      - name: Build project
        run: cargo build --release

      - name: Run basic tests
        run: cargo test --release